// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import { TestBase } from "./TestBase.sol";
import { RescueCoin } from "./AdminFeatures.t.sol";
import { RankedAuction } from "../src/RankedAuction.sol";
import { AuctionEdition } from "../src/AuctionEdition.sol";
import { IERC2981 } from "@openzeppelin/contracts/interfaces/IERC2981.sol";
import { ICreatorToken } from "@limitbreak/creator-token-standards/src/interfaces/ICreatorToken.sol";
import { SignedZone } from "./vendor/opensea-zone/src/main/zones/signed-zone/signed-zone-sub-1/SignedZone.sol";
import {
    StrictAuthorizedTransferSecurityRegistry
} from "./vendor/opensea/src/StrictAuthorizedTransferSecurityRegistry.sol";
import { TransferSecurityLevels } from "./vendor/opensea/src/interfaces/IStrictAuthorizedTransferSecurityRegistry.sol";
import {
    AdvancedOrder,
    OrderParameters,
    OrderComponents,
    OfferItem,
    ConsiderationItem,
    CriteriaResolver
} from "./vendor/opensea-zone/src/types/lib/ConsiderationStructs.sol";
import { ItemType, OrderType } from "./vendor/opensea-zone/src/types/lib/ConsiderationEnums.sol";

interface IConduitTest {
    function updateChannel(address channel, bool isOpen) external;
}

interface ISeaportTest {
    function information() external view returns (string memory, bytes32, address);
    function getOrderHash(OrderComponents calldata order) external view returns (bytes32);
    function fulfillAdvancedOrder(
        AdvancedOrder calldata order,
        CriteriaResolver[] calldata resolvers,
        bytes32 conduitKey,
        address recipient
    ) external payable returns (bool);
}

/// @dev Test-only representative of another royalty-aware marketplace, not a production exchange.
contract OtherRoyaltyMarketplaceFixture {
    function buy(AuctionEdition token, address seller, uint256 tokenId) external payable {
        (address creator, uint256 royalty) = token.royaltyInfo(tokenId, msg.value);
        token.safeTransferFrom(seller, msg.sender, tokenId);
        (bool paidCreator,) = payable(creator).call{ value: royalty }("");
        (bool paidSeller,) = payable(seller).call{ value: msg.value - royalty }("");
        require(paidCreator && paidSeller, "Payment failed");
    }
}

/// @dev Actual Seaport 1.6 runtime + unmodified verified SignedZone/registry sources.
///      Signatures are generated by a local test signer, not OpenSea's live API.
contract OpenSeaIntegrationTest is TestBase {
    address constant SEAPORT = 0x0000000000000068F116a894984e2DB1123eB395;
    address constant CONDUIT = 0x1E0049783F008A0085193E00003D00cd54003c71;
    bytes32 constant CONDUIT_KEY = 0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000;
    uint256 constant SELLER_KEY = 0x515151;
    uint256 constant ZONE_SIGNER_KEY = 0x717171;
    ISeaportTest seaport = ISeaportTest(SEAPORT);
    bytes32 constant DOMAIN_TYPE =
        keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)");
    bytes32 constant SIGNED_ORDER_TYPE =
        keccak256("SignedOrder(address fulfiller,uint64 expiration,bytes32 orderHash,bytes context)");

    function setUp() public override {
        super.setUp();
        RankedAuction.Config memory c = config();
        c.royaltyBps = 1000;
        auction = new RankedAuction(c);
        edition = auction.edition();
        market = edition.marketplace();
        configureTrading(edition, payoutWallet);
        alice = vm.addr(SELLER_KEY);
        mintForMarket();
        vm.etch(SEAPORT, vm.parseJsonBytes(vm.readFile("test/vendor/Seaport-1.6-runtime.json"), ".runtime"));
        vm.etch(CONDUIT, vm.parseJsonBytes(vm.readFile("test/vendor/OpenSea-conduit-runtime.json"), ".runtime"));
        (,, address conduitController) = seaport.information();
        vm.prank(conduitController);
        IConduitTest(CONDUIT).updateChannel(SEAPORT, true);
        // Force domain recomputation after moving the exact SignedZone runtime to its canonical address.
        vm.chainId(1);
        SignedZone zone = new SignedZone("OpenSea SignedZone");
        vm.etch(edition.OPENSEA_SIGNED_ZONE(), address(zone).code);
        vm.chainId(31337);
        (bool ok,) = edition.OPENSEA_SIGNED_ZONE()
            .call(abi.encodeWithSignature("updateSigner(address,bool)", vm.addr(ZONE_SIGNER_KEY), true));
        assertTrue(ok);
        vm.prank(alice);
        edition.setApprovalForAll(SEAPORT, true);
    }

    function registry() internal view returns (StrictAuthorizedTransferSecurityRegistry) {
        return StrictAuthorizedTransferSecurityRegistry(edition.OPENSEA_TRANSFER_VALIDATOR());
    }

    function _components(OrderParameters memory p) internal pure returns (OrderComponents memory) {
        return OrderComponents(
            p.offerer,
            p.zone,
            p.offer,
            p.consideration,
            p.orderType,
            p.startTime,
            p.endTime,
            p.zoneHash,
            p.salt,
            p.conduitKey,
            0
        );
    }

    function _signSeller(AdvancedOrder memory order) internal view returns (bytes memory) {
        (, bytes32 domain,) = seaport.information();
        bytes32 digest =
            keccak256(abi.encodePacked(hex"1901", domain, seaport.getOrderHash(_components(order.parameters))));
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(SELLER_KEY, digest);
        return abi.encodePacked(r, s, v);
    }

    function _zoneData(bytes32 orderHash, address fulfiller, uint64 expires, uint256 signerKey)
        internal
        view
        returns (bytes memory)
    {
        return _zoneDataForIdentifier(orderHash, fulfiller, expires, signerKey, 0);
    }

    function _zoneDataForIdentifier(
        bytes32 orderHash,
        address fulfiller,
        uint64 expires,
        uint256 signerKey,
        uint256 identifier
    ) internal view returns (bytes memory) {
        // SIP-7 substandard 8 binds the first consideration identifier (0 for ETH, NFT ID for an offer).
        bytes memory context = abi.encodePacked(bytes1(0x08), bytes32(identifier), edition.OPENSEA_TRANSFER_VALIDATOR());
        bytes32 domain = keccak256(
            abi.encode(
                DOMAIN_TYPE,
                keccak256("OpenSea SignedZone"),
                keccak256("2.0"),
                block.chainid,
                edition.OPENSEA_SIGNED_ZONE()
            )
        );
        bytes32 digest = keccak256(
            abi.encodePacked(
                hex"1901",
                domain,
                keccak256(abi.encode(SIGNED_ORDER_TYPE, fulfiller, expires, orderHash, keccak256(context)))
            )
        );
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(signerKey, digest);
        bytes32 vs = bytes32(uint256(s) | (uint256(v - 27) << 255));
        return abi.encodePacked(bytes1(0), fulfiller, expires, r, vs, context);
    }

    function _order(uint256 id, uint256 price, uint256 royalty, OrderType kind)
        internal
        view
        returns (AdvancedOrder memory a)
    {
        OfferItem[] memory offers = new OfferItem[](1);
        offers[0] = OfferItem(ItemType.ERC721, address(edition), id, 1, 1);
        ConsiderationItem[] memory payments = new ConsiderationItem[](royalty == 0 ? 1 : 2);
        payments[0] =
            ConsiderationItem(ItemType.NATIVE, address(0), 0, price - royalty, price - royalty, payable(alice));
        if (royalty != 0) {
            payments[1] = ConsiderationItem(
                ItemType.NATIVE, address(0), 0, royalty, royalty, payable(edition.royaltyRecipient())
            );
        }
        a.parameters = OrderParameters(
            alice,
            edition.OPENSEA_SIGNED_ZONE(),
            offers,
            payments,
            kind,
            block.timestamp - 1,
            block.timestamp + 1 hours,
            bytes32(0),
            id,
            bytes32(0),
            payments.length
        );
        a.numerator = 1;
        a.denominator = 1;
        a.signature = _signSeller(a);
        a.extraData = _zoneData(
            seaport.getOrderHash(_components(a.parameters)), bob, uint64(block.timestamp + 5 minutes), ZONE_SIGNER_KEY
        );
    }

    function _buy(AdvancedOrder memory order, uint256 price) internal {
        vm.prank(bob);
        seaport.fulfillAdvancedOrder{ value: price }(order, new CriteriaResolver[](0), bytes32(0), bob);
    }

    function testCreatorTokenInterfacesAndStrictRegistryConfiguration() public view {
        assertTrue(edition.supportsInterface(type(ICreatorToken).interfaceId));
        assertTrue(edition.supportsInterface(type(IERC2981).interfaceId));
        assertTrue(edition.supportsInterface(0x80ac58cd));
        assertTrue(edition.supportsInterface(0x49064906));
        (bytes4 selector, bool isView) = edition.getTransferValidationFunction();
        assertEq(selector, bytes4(0xcaee23ea));
        assertTrue(isView);
        assertEq(edition.owner(), payoutWallet);
        assertEq(edition.getTransferValidator(), edition.OPENSEA_TRANSFER_VALIDATOR());
        assertTrue(registry().isAccountAuthorizerOfCollection(address(edition), edition.OPENSEA_SIGNED_ZONE()));
        assertTrue(registry().isAccountWhitelistedByCollection(address(edition), address(market)));
        assertFalse(registry().isAccountWhitelistedByCollection(address(edition), SEAPORT));
        assertEq(registry().listOwners(edition.tradingListId()), address(edition));
        assertFalse(edition.autoApproveTransfersFromValidator());
        assertEq(edition.contractURI(), "ipfs://edition-metadata/contract.json");
    }

    function testActualSeaportAndSignedZonePayTenPercentAndClearAuthorization() public {
        uint256 creatorBefore = payoutWallet.balance;
        uint256 sellerBefore = alice.balance;
        _buy(_order(1, 1 ether, 0.1 ether, OrderType.FULL_RESTRICTED), 1 ether);
        assertEq(edition.ownerOf(1), bob);
        assertEq(payoutWallet.balance - creatorBefore, 0.1 ether);
        assertEq(alice.balance - sellerBefore, 0.9 ether);
        assertEq(edition.transferNonce(1), 1);
        assertEq(market.pendingRoyalties(), 0);
        vm.prank(bob);
        edition.setApprovalForAll(SEAPORT, true);
        vm.prank(SEAPORT);
        vm.expectRevert();
        edition.transferFrom(bob, carol, 1);
    }

    function _conduitOrder(uint256 royalty, OrderType kind) internal view returns (AdvancedOrder memory order) {
        order = _order(1, 1 ether, royalty, kind);
        order.parameters.conduitKey = CONDUIT_KEY;
        order.signature = _signSeller(order);
        order.extraData = _zoneData(
            seaport.getOrderHash(_components(order.parameters)),
            bob,
            uint64(block.timestamp + 5 minutes),
            ZONE_SIGNER_KEY
        );
    }

    function testActualOpenSeaConduitPaysTenPercent() public {
        vm.startPrank(alice);
        edition.setApprovalForAll(SEAPORT, false);
        edition.setApprovalForAll(CONDUIT, true);
        vm.stopPrank();
        uint256 beforeCreator = payoutWallet.balance;
        _buy(_conduitOrder(0.1 ether, OrderType.FULL_RESTRICTED), 1 ether);
        assertEq(edition.ownerOf(1), bob);
        assertEq(payoutWallet.balance - beforeCreator, 0.1 ether);
    }

    function testOpenSeaConduitWorksWithInertAutoApprovalFlagEnabled() public {
        vm.prank(payoutWallet);
        edition.setAutomaticApprovalOfTransfersFromValidator(true);
        assertFalse(edition.isApprovedForAll(alice, edition.getTransferValidator()));
        testActualOpenSeaConduitPaysTenPercent();
    }

    function testOpenSeaERC20OfferWorksWithInertAutoApprovalFlagEnabled() public {
        vm.prank(payoutWallet);
        edition.setAutomaticApprovalOfTransfersFromValidator(true);
        assertFalse(edition.isApprovedForAll(alice, edition.getTransferValidator()));
        testActualSeaportERC20OfferAcceptancePaysTenPercent();
    }

    function testConduitApprovalAloneCannotBypassRoyalties() public {
        vm.prank(alice);
        edition.setApprovalForAll(CONDUIT, true);
        AdvancedOrder memory order = _conduitOrder(0, OrderType.FULL_OPEN);
        vm.expectRevert();
        _buy(order, 1 ether);
        assertEq(edition.ownerOf(1), alice);
    }

    function testConfigurationRejectsMissingRegistryAndUnauthorizedCaller() public {
        vm.prank(bob);
        vm.expectRevert(AuctionEdition.Unauthorized.selector);
        edition.configureEnforcedTrading();
        vm.etch(edition.OPENSEA_TRANSFER_VALIDATOR(), "");
        vm.prank(payoutWallet);
        vm.expectRevert(AuctionEdition.InvalidConfiguration.selector);
        edition.configureEnforcedTrading();
        vm.prank(alice);
        vm.expectRevert(AuctionEdition.RoyaltyTransferRequired.selector);
        edition.transferFrom(alice, bob, 1);
    }

    function testOrdinarySeaportOrderCannotBypassRoyalties() public {
        AdvancedOrder memory order = _order(1, 1 ether, 0, OrderType.FULL_OPEN);
        order.extraData = "";
        vm.expectRevert();
        _buy(order, 1 ether);
        assertEq(edition.ownerOf(1), alice);
        assertEq(edition.transferNonce(1), 0);
    }

    function testRemovingRoyaltyCannotReuseZoneAuthorization() public {
        bytes memory authorization = _order(1, 1 ether, 0.1 ether, OrderType.FULL_RESTRICTED).extraData;
        AdvancedOrder memory freeRoyaltyOrder = _order(1, 1 ether, 0, OrderType.FULL_RESTRICTED);
        freeRoyaltyOrder.extraData = authorization;
        vm.expectRevert();
        _buy(freeRoyaltyOrder, 1 ether);
        assertEq(edition.ownerOf(1), alice);
    }

    function testMissingFakeExpiredAndWrongFulfillerSignaturesFail() public {
        AdvancedOrder memory order = _order(1, 1 ether, 0.1 ether, OrderType.FULL_RESTRICTED);
        bytes32 orderHash = seaport.getOrderHash(_components(order.parameters));
        order.extraData = "";
        vm.expectRevert();
        _buy(order, 1 ether);
        order.extraData = _zoneData(orderHash, bob, uint64(block.timestamp + 100), 0xBAD);
        vm.expectRevert();
        _buy(order, 1 ether);
        order.extraData = _zoneData(orderHash, bob, uint64(block.timestamp - 1), ZONE_SIGNER_KEY);
        vm.expectRevert();
        _buy(order, 1 ether);
        order.extraData = _zoneData(orderHash, carol, uint64(block.timestamp + 100), ZONE_SIGNER_KEY);
        vm.expectRevert();
        _buy(order, 1 ether);
        assertEq(edition.ownerOf(1), alice);
        assertEq(edition.transferNonce(1), 0);
    }

    function testZoneAuthorizationCannotMoveAnotherToken() public {
        bytes memory authorization = _order(1, 1 ether, 0.1 ether, OrderType.FULL_RESTRICTED).extraData;
        AdvancedOrder memory other = _order(2, 1 ether, 0.1 ether, OrderType.FULL_RESTRICTED);
        other.extraData = authorization;
        vm.expectRevert();
        _buy(other, 1 ether);
        assertEq(edition.ownerOf(2), alice);
    }

    function testActualSeaportERC20OfferAcceptancePaysTenPercent() public {
        RescueCoin paymentToken = new RescueCoin();
        uint256 buyerKey = 0xB0BAAA;
        address buyer = vm.addr(buyerKey);
        paymentToken.mint(buyer, 1 ether);
        vm.prank(buyer);
        paymentToken.approve(SEAPORT, 1 ether);
        vm.prank(alice);
        paymentToken.approve(SEAPORT, 0.1 ether);

        OfferItem[] memory offered = new OfferItem[](1);
        offered[0] = OfferItem(ItemType.ERC20, address(paymentToken), 0, 1 ether, 1 ether);
        ConsiderationItem[] memory requested = new ConsiderationItem[](2);
        requested[0] = ConsiderationItem(ItemType.ERC721, address(edition), 1, 1, 1, payable(buyer));
        requested[1] =
            ConsiderationItem(ItemType.ERC20, address(paymentToken), 0, 0.1 ether, 0.1 ether, payable(payoutWallet));
        AdvancedOrder memory offer;
        offer.parameters = OrderParameters(
            buyer,
            edition.OPENSEA_SIGNED_ZONE(),
            offered,
            requested,
            OrderType.FULL_RESTRICTED,
            block.timestamp - 1,
            block.timestamp + 1 hours,
            bytes32(0),
            99,
            bytes32(0),
            2
        );
        offer.numerator = 1;
        offer.denominator = 1;
        bytes32 orderHash = seaport.getOrderHash(_components(offer.parameters));
        (, bytes32 domain,) = seaport.information();
        (uint8 v, bytes32 r, bytes32 sigS) =
            vm.sign(buyerKey, keccak256(abi.encodePacked(hex"1901", domain, orderHash)));
        offer.signature = abi.encodePacked(r, sigS, v);
        offer.extraData =
            _zoneDataForIdentifier(orderHash, alice, uint64(block.timestamp + 5 minutes), ZONE_SIGNER_KEY, 1);
        vm.prank(alice);
        assertTrue(seaport.fulfillAdvancedOrder(offer, new CriteriaResolver[](0), bytes32(0), alice));
        assertEq(edition.ownerOf(1), buyer);
        assertEq(paymentToken.balanceOf(payoutWallet), 0.1 ether);
        assertEq(paymentToken.balanceOf(alice), 0.9 ether);
        assertEq(paymentToken.balanceOf(buyer), 0);
        assertEq(edition.transferNonce(1), 1);
    }

    function testFilledSeaportOrderCannotReplay() public {
        AdvancedOrder memory order = _order(1, 1 ether, 0.1 ether, OrderType.FULL_RESTRICTED);
        _buy(order, 1 ether);
        vm.expectRevert();
        _buy(order, 1 ether);
        assertEq(edition.transferNonce(1), 1);
    }

    function testOtherCompatibleMarketplaceTradesWithoutCustomMarket() public {
        OtherRoyaltyMarketplaceFixture other = new OtherRoyaltyMarketplaceFixture();
        vm.startPrank(payoutWallet);
        uint120 list = registry().createListCopy("Another compatible marketplace", edition.tradingListId());
        registry().addAccountToWhitelist(list, address(other));
        registry().applyListToCollection(address(edition), list);
        vm.stopPrank();
        vm.prank(alice);
        edition.setApprovalForAll(address(other), true);
        uint256 beforeCreator = payoutWallet.balance;
        vm.prank(bob);
        other.buy{ value: 1 ether }(edition, alice, 1);
        assertEq(edition.ownerOf(1), bob);
        assertEq(payoutWallet.balance - beforeCreator, 0.1 ether);
        assertEq(market.totalCredits(), 0);
    }

    function testRotationMovesCreatorTokenAdministrationAndNewSaleRoyalties() public {
        vm.prank(payoutWallet);
        auction.proposePayoutWallet(carol);
        vm.prank(carol);
        auction.acceptPayoutWallet();
        assertEq(edition.owner(), carol);
        vm.startPrank(payoutWallet);
        vm.expectRevert(AuctionEdition.Unauthorized.selector);
        edition.setTransferValidator(address(0));
        vm.expectRevert(AuctionEdition.Unauthorized.selector);
        edition.setAutomaticApprovalOfTransfersFromValidator(true);
        vm.expectRevert(AuctionEdition.Unauthorized.selector);
        edition.configureEnforcedTrading();
        vm.stopPrank();
        uint256 beforeCreator = carol.balance;
        _buy(_order(1, 1 ether, 0.1 ether, OrderType.FULL_RESTRICTED), 1 ether);
        assertEq(carol.balance - beforeCreator, 0.1 ether);
    }

    function testUnsetValidatorCannotDisableEnforcement() public {
        vm.prank(payoutWallet);
        edition.setTransferValidator(address(0));
        vm.prank(alice);
        vm.expectRevert(AuctionEdition.RoyaltyTransferRequired.selector);
        edition.transferFrom(alice, bob, 1);
        vm.prank(payoutWallet);
        edition.configureEnforcedTrading();
        _buy(_order(1, 1 ether, 0.1 ether, OrderType.FULL_RESTRICTED), 1 ether);
    }

    function testUnconfiguredEditionCanMintButCannotTransfer() public {
        AuctionEdition fresh = new AuctionEdition("Fresh", "F", "ipfs://fresh/", 1000);
        fresh.mint(alice, one(1));
        vm.prank(alice);
        fresh.setApprovalForAll(SEAPORT, true);
        vm.prank(SEAPORT);
        vm.expectRevert(AuctionEdition.RoyaltyTransferRequired.selector);
        fresh.transferFrom(alice, bob, 1);
        assertEq(fresh.ownerOf(1), alice);
    }

    function testOpenSeaTransferInvalidatesExistingLocalListing() public {
        vm.prank(alice);
        uint256 listing = market.list(1, 1 ether, uint64(block.timestamp + 1 hours));
        _buy(_order(1, 1 ether, 0.1 ether, OrderType.FULL_RESTRICTED), 1 ether);
        vm.startPrank(bob);
        edition.setApprovalForAll(address(market), true);
        uint256 returnListing = market.list(1, 0.1 ether, uint64(block.timestamp + 1 hours));
        vm.stopPrank();
        vm.prank(alice);
        market.buy{ value: 0.1 ether }(returnListing, alice);
        assertEq(edition.ownerOf(1), alice);
        assertEq(edition.transferNonce(1), 2);
        vm.prank(carol);
        vm.expectRevert();
        market.buy{ value: 1 ether }(listing, carol);
    }
}
